apiVersion: apps/v1
kind: Deployment
metadata:
  name:rule-of-thumb
spec:
  replicas: 3
  selector:
    matchLabels:
      app:rule-of-thumb
  template:
    metadata:
      labels:
        app:rule-of-thumb
    spec:
      containers:
      - name:rule-of-thumb
        image: gcr.io/zemoga-ui-prod/github.com/juandresyn/rule-of-thumb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name:rule-of-thumb
spec:
  type: NodePort
  selector:
    app:rule-of-thumb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:rule-of-thumb-ingress
  namespace: "default"
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: "ifw-one-v2-ssl"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name:rule-of-thumb
              port:
                number: 80
